name: add-merit-badger
on:
  pull_request_target:
    types:
      - opened

jobs:
  merit-badges:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: aws-github-ops/github-merit-badger@main
        id: github-merit-badger
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          badges: '[first-time-contributor,repeat-contributor,allstar-contributor]'
          thresholds: '[0,1,5]'
